### ISSUE TITLE
Getting Error when downloading packages

### ISSUE THREAD

**Issue by Codzaa** [pion/offline-browser-communication#13]
![image](https://user-images.githubusercontent.com/35093657/142587302-2e7d13f9-e394-4608-8497-4d3792adc313.png)

When trying to run the the app I receive this error

What are my doing wrong

By the way on Windows I couldn't use `go run *go` , I had to use `go run .` instead

**Comment by Sean-Der** [comment]
https://github.com/pion/offline-browser-communication#i-need-to-update-the-dtls-fingerprint Mind updating the certificate with a PR, thank you!

**Comment by Sean-Der** [comment]
Hey @Codzaa 

I updated the certificate. Would you mind trying again?

**Comment by Codzaa** [comment]
Hi @Sean-Der 

Thanks for replying, maybe I am doing something wrong, but Im getting another message.

I pulled a new version of the updated repository and this time I get the following message

![image](https://user-images.githubusercontent.com/35093657/142713519-c6a096d7-c485-4dce-a0cb-d1e507b06749.png)

**Comment by Sean-Der** [comment]
@Codzaa Sorry about that! Did a `go mod tidy` and now it works.

Thanks for the patience

**Comment by Codzaa** [comment]
Thanks @Sean-Der  its now working :)
