### ISSUE TITLE
Error when trying to run script.

### ISSUE THREAD

**Issue by wwwonka** [pion/offline-browser-communication#2]
I am trying to run the script and after downloading the dependencies, the terminal throws me this error:

`panic: InvalidAccessError: x509Cert expired

goroutine 1 [running]:
main.panicIfErr(...)
	/Users/-/Desktop/offline-browser-communication-master/server.go:110
main.main()
	/Users/-/Desktop/offline-browser-communication-master/server.go:50 +0x3b2
exit status 2
`

**Comment by Sean-Der** [comment]
Thanks for the report @wwwonka, this is fixed in master! When you get a chance mind trying again?

**Comment by wwwonka** [comment]
Done! It works now.
And it's truly remarkable. See you on the slack channel...!
